# Generated by Django 5.0.4 on 2026-05-01 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_add_description_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم المشروع بالعربية')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='اسم المشروع بالإنجليزية')),
                ('description_ar', models.TextField(blank=True, default='', verbose_name='وصف المشروع بالعربية')),
                ('description_en', models.TextField(blank=True, default='', verbose_name='وصف المشروع بالإنجليزية')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('products', models.ManyToManyField(blank=True, related_name='projects', to='products.product', verbose_name='المنتجات المستخدمة')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'مشاريع',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000, verbose_name='رابط الصورة في R2')),
                ('image_key', models.CharField(max_length=500, verbose_name='مفتاح الصورة في R2')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255, verbose_name='نص بديل')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_cover', models.BooleanField(default=False, verbose_name='صورة الغلاف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'صورة مشروع',
                'verbose_name_plural': 'صور المشاريع',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_active'], name='projects_pr_is_acti_f7dee7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['sort_order'], name='projects_pr_sort_or_584f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectimage',
            index=models.Index(fields=['project', 'sort_order'], name='projects_pr_project_99c89f_idx'),
        ),
    ]
