# Generated by Django 5.0.4 on 2026-05-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location_ar',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='الموقع بالعربية'),
        ),
        migrations.AddField(
            model_name='project',
            name='location_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='الموقع بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سنة المشروع'),
        ),
    ]
